In [14]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
import math

V1 = np.array([[2],
               [1],
               [0], ])
V2 = np.array([[4],
               [2],
               [1], ])


In [15]:
print("V1\n",V1,"\nV2\n",V2)

V1
 [[2]
 [1]
 [0]] 
V2
 [[4]
 [2]
 [1]]


In [16]:
import math
U1 = V1
U1T = np.transpose(U1)
# print("U1\n", U1)
U1len = math.sqrt(U1T @ U1)

In [17]:
print("U1 długosc: ", U1len)

U1 długosc:  2.23606797749979


In [18]:
E1 = (U1) / U1len
print(E1)

[[0.89442719]
 [0.4472136 ]
 [0.        ]]


In [19]:
projU1odV2 = (np.transpose(V2) @ U1) / (np.transpose(U1) @ U1) * U1
print(projU1odV2)

[[4.]
 [2.]
 [0.]]


In [20]:
U2 = V2 - projU1odV2
U2T = np.transpose(U2)
print("U2", U2)

U2 [[0.]
 [0.]
 [1.]]


In [21]:
U2len = math.sqrt(U2T @ U2)
print("U2 długosc: ", U2len)
R=np.hstack((U1, U2))

U2 długosc:  1.0


In [22]:
E2 = (U2) / U2len
print(E2)

[[0.]
 [0.]
 [1.]]
