In [30]:
import math
import numpy as np

In [31]:
V1T = np.array([
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,-1,-1,-1,-1],
    [1,1,-1,-1,0,0,0,0],
    [0,0,0,0,1,1,-1,-1],
    [1,-1,0,0,0,0,0,0],
    [0,0,1,-1,0,0,0,0],
    [0,0,0,0,1,-1,0,0],
    [0,0,0,0,0,0,1,-1],
])

In [32]:
V1 = np.transpose(V1T)
V2 = V1T @ V1

In [33]:
print("V2\n", V2)

V2
 [[8 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 2]]


In [34]:
jedn=[]
print(jedn)

[]


In [35]:
for arr in np.transpose(V1):
    zm = math.sqrt(np.dot(arr, arr))
    jedn.append(arr / zm)
print(jedn)

[array([0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339,
       0.35355339, 0.35355339, 0.35355339]), array([ 0.35355339,  0.35355339,  0.35355339,  0.35355339, -0.35355339,
       -0.35355339, -0.35355339, -0.35355339]), array([ 0.5,  0.5, -0.5, -0.5,  0. ,  0. ,  0. ,  0. ]), array([ 0. ,  0. ,  0. ,  0. ,  0.5,  0.5, -0.5, -0.5]), array([ 0.70710678, -0.70710678,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ]), array([ 0.        ,  0.        ,  0.70710678, -0.70710678,  0.        ,
        0.        ,  0.        ,  0.        ]), array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.70710678,
       -0.70710678,  0.        ,  0.        ]), array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.70710678, -0.70710678])]


In [36]:
np.set_printoptions(suppress=True)
jedn1 = np.transpose(jedn)
print(jedn1)

[[ 0.35355339  0.35355339  0.5         0.          0.70710678  0.
   0.          0.        ]
 [ 0.35355339  0.35355339  0.5         0.         -0.70710678  0.
   0.          0.        ]
 [ 0.35355339  0.35355339 -0.5         0.          0.          0.70710678
   0.          0.        ]
 [ 0.35355339  0.35355339 -0.5         0.          0.         -0.70710678
   0.          0.        ]
 [ 0.35355339 -0.35355339  0.          0.5         0.          0.
   0.70710678  0.        ]
 [ 0.35355339 -0.35355339  0.          0.5         0.          0.
  -0.70710678  0.        ]
 [ 0.35355339 -0.35355339  0.         -0.5         0.          0.
   0.          0.70710678]
 [ 0.35355339 -0.35355339  0.         -0.5         0.          0.
   0.         -0.70710678]]


In [37]:
jedn_zaok=np.round(np.transpose(jedn1) @ jedn1, decimals=1)

przek = np.array([8, 6 ,2 ,3 ,4 ,6, 6, 5])
przek1= np.transpose(jedn1) @ przek
print(jedn_zaok)

[[ 1.  0.  0.  0. -0. -0. -0. -0.]
 [ 0.  1.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  1.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  1.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  1.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  1.]]


In [38]:
print(przek1)

[14.14213562 -0.70710678  4.5        -0.5         1.41421356 -0.70710678
 -1.41421356  0.70710678]
