In [16]:
from numpy import array,round
from scipy.linalg import svd

In [17]:
A = array([[3, 1, 1], [-1, 3, 1]])

In [18]:
print("A=",A)

A= [[ 3  1  1]
 [-1  3  1]]


In [19]:
U, S, V_T = svd(A)

In [20]:
print("U=")
print(U)
# singular values
print("S=")
print(S)
#right singular vectors
print("V_T=")
print(V_T)

U=
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S=
[3.46410162 3.16227766]
V_T=
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [21]:
#######################

In [484]:
import numpy as np
from scipy.linalg import eigh,norm,eig
step=0

In [515]:
# A = array([[-5, 2, 3], [2,5, 1],[-3,1,-5]])
# A = np.array([[3, 1, 1], [-1, 3, 1]])

A = array([[1, 1], [0,1],[1,0]])
if(len(A)>len(A[0])):
    step=eigh(A@A.T)
    ev,U=step
    v0=A.T@U[:,2]/norm(A.T@U[:,2])
    v1=A.T@U[:,1]/norm(A.T@U[:,1])
    V=np.array([v0,v1])
    V = V[~np.all(V == 0, axis=1)]#USUWA zerowe wiersze
else:
    step=eig(A.T@A)
    ev,V=step
    u0=A@V[:,0]/norm(A@V[:,0])
    u1=A@V[:,1]/norm(A@V[:,1])#sigma-1*A*V
    u2=A@V[:,2]/norm(A@V[:,2])
    U= np.array([u0,u1,u2]).T
    U = U[~np.all(U == 0, axis=1)]#USUWA zerowe wiersze

# D=round(V @ A @ U.T, decimals=5)

print(U,"\n--------------\n",v0)

[[-8.16496581e-01 -5.77350269e-01 -1.57009246e-16]
 [-4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-4.08248290e-01  5.77350269e-01  7.07106781e-01]] 
--------------
 [ 0.70710678 -0.70710678]


In [511]:
step

(array([1.77635684e-15, 1.00000000e+00, 3.00000000e+00]),
 array([[ 0.57735027,  0.        ,  0.81649658],
        [-0.57735027, -0.70710678,  0.40824829],
        [-0.57735027,  0.70710678,  0.40824829]]))

In [502]:
# ev,V=step

In [503]:
# u0=A@V[:,0]/norm(A@V[:,0])
# u1=A@V[:,1]/norm(A@V[:,1])
# u2=A@V[:,2]/norm(A@V[:,2])
# ev

In [504]:
# U= np.array([u0,u1,u2]).T
U

array([[-0.77151675,  0.26726124,  0.6147259 ],
       [ 0.15430335, -0.80178373,  0.56903076],
       [-0.6172134 , -0.53452248, -0.54618318]])

In [505]:
# U = U[~np.all(U == 0, axis=1)]#USUWA zerowe wiersze
V

array([[ 0.96362411, -0.26726124, -0.04756101],
       [-0.22237479, -0.80178373,  0.56499976],
       [ 0.14824986,  0.53452248,  0.82371914]])

In [506]:
D=round(U.T @ A@ V, decimals=5)
D = D[~np.all(D == 0, axis=1)]

# idx = np.argwhere(np.all(D[..., :] == 0, axis=0))
# D = np.delete(D, idx, axis=1)
D

array([[ 6.245  ,  0.     , -0.30823],
       [ 0.     ,  5.     ,  0.     ],
       [-0.30823,  0.     ,  6.245  ]])

In [507]:
print("A=U*E*V^T",round(U@D@V.T))

A=U*E*V^T [[-5.  2.  3.]
 [ 2.  5.  1.]
 [-3.  1. -5.]]


In [415]:
A = array([[-5, 2, 3], [2,5, 1],[-3,1,-5]])